### ISSUE TITLE
Bug: camera boxes forget their defense computer

### ISSUE THREAD

**Issue by Mirka1405** [Red050911/DefenseSystems#1]
# Bug Report
**Please explain your issue**: After leaving and reloading the world, camera boxes do not detect enemies.
**MC Version**: 1.18.2
**DefenseSystems version**: 1.0.0
**Fabric Loader version**: 0.14.19
**Fabric API version**: 0.67.0
**Platform**: Windows
**Steps to reproduce bug**: Set up defence, then leave and reload the world. After breaking and placing back the camera box, everything works as usual.

**Comment by Mirka1405** [comment]
Radars don't seem to have the same issue. I only checked telescopic IR camera box.

**Comment by ImplicitSaber** [comment]
I wasn't able to reproduce this bug. Are there any other conditions in the environment than just the computer? I do know of a bug involving snow that prevents camera vision.

**Comment by Mirka1405** [comment]
Plains & bunch of caves underneath. Haven't experimented a lot.
