### ISSUE TITLE
Bug: Invalid Player Data

### ISSUE THREAD

**Issue by teny1989** [Red050911/DefenseSystems#2]
# Bug Report
**Please explain your issue**: When Defense Systems is installed alongside Lithium, whether a saved world or creating a brand new world will cause Invalid Player Data
**MC Version**: 1.19.4
**DefenseSystems version**: 1.0.0
**Fabric Loader version**: 0.14.19
**Fabric API version**: 0.80
**Platform**: Windows
**Steps to reproduce bug**: Launch Minecraft with both Lithium and Defense Systems

**Comment by teny1989** [comment]
Had to edit after retrying a test

**Comment by ImplicitSaber** [comment]
Was able to reproduce the bug on both 1.18.2 and 1.19.4. Adding a null check to prevent this.

**Comment by ImplicitSaber** [comment]
Fixed on 1.18.2. Release coming out soon.

**Comment by ImplicitSaber** [comment]
Fixed on 1.19.4. Release coming out soon.

**Comment by ImplicitSaber** [comment]
Issue is fixed on both 1.18.2 and 1.19.4. GitHub and Modrinth releases are ready right now, CurseForge releases are under review.
